server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dbdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql
bot:
  token: ${BOT_TOKEN:7641856824:AAFw9Ay8iT30_nLm7gVoH7zFmZk7bcWSJBo}
  username: ${BOT_USERNAME:@jBlazzzyBot}